name: 'Aqara/Xiaomi Switch and Button v26 mod by sk'
packageKey: 'lumi-switch'
description: 'Aqara/Xiaomi Switch and Button origninal repository by veonua https://github.com/veonua/SmartThingsEdge-Xiaomi\n Modified by sk to support Z1 Pro 3 nd 4 Gang here https://github.com/sk-edge-drivers/SmartThingsEdge-Xiaomi'
permissions:
  zigbee: {}
